### PR TITLE
Temporary PR to allow CI to generate preview for testing.

### PR DESCRIPTION
**Pull request by willis102**

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/e1865cf51e2fb5253c8fb3989bfd076d5ac188e6/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/934b1e6d13dc04a11e2a18dc6fc4af632320f6ed/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://doctest3.s3-website.eu-west-2.amazonaws.com/tk-doc-generator/1f5b395a73ed403f5dbb66a04395c010f3f5dc07/index.html)

**Comment by willis102** [comment]
This PR should not be merged, and the branch should be deleted.

**Pull request closed without merging**
