### PR TITLE
Add debugging info

### PR DESCRIPTION
**Pull request by carlos-villavicencio-adsk**
Adds debugging info when there are duplicates pages UIDs

Relates to https://github.com/shotgunsoftware/developer.shotgunsoftware.com/pull/426

### CODE REVIEW

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e0d07eeec01e302631f70659731175d0b895391e/index.html)

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/b342c63aee742e85d07b16e4f066159af3cfaa32/index.html)

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e566f1180544c9a10112cb99daba166677a063be/index.html)

**Review by NorberMV — APPROVED** [review]
LGTM !
The debug info looks more descriptive in CI now:
Screenshot 2023-04-12 at 11 43 02 AM

**Pull request merged**
