### PR TITLE
SG-30020 Improve error handling when running commands

### PR DESCRIPTION
**Pull request by carlos-villavicencio-adsk**
Raises when external command returns code different than zero.

### CODE REVIEW

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/64cf31698446047332d49005cfa49a3c63e96da6/index.html)

**Review by julien-lang — CHANGES_REQUESTED** [review]
Can you add the ticket ID in the PR title please?

**Comment by carlos-villavicencio-adsk** [comment]
QAed here: https://github.com/shotgunsoftware/developer.shotgunsoftware.com/pull/421

**Review by julien-lang — APPROVED** [review]
LGTM!

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/2a4c8fb860fe8aadb29630a53e12966a2af48b3a/index.html)

**Pull request merged**
