### PR TITLE
Updates to the Cloudfront S3 bucket URL.

### PR DESCRIPTION
**Pull request by thebeeland**
Per DevOps request.

### CODE REVIEW

**Review by jfboismenu — CHANGES_REQUESTED** [review]
Seems like you'll need to update the AWS key as well. The tests are failing.

**Review by comeaug — APPROVED** [review]

**Comment by carlos-villavicencio-adsk** [comment]
Closed since we migrated from Travis

**Comment by shotgun-server** [comment]
What's the workflow for the doc now? is it still published to that bucket?

edit
bad login, that was from me @comeaug

**Comment by carlos-villavicencio-adsk** [comment]
Yes, it is still using sg-devdocs.s3-website-us-east-1.amazonaws.com

**Comment by comeaug** [comment]
The security team requested that all public buckets be fronted by Cloudfront hence this PR to use the sg-devdocs.ems.autodesk.com cloudfront endpoint. I'm not sure why it has never been merged. I think it might still be relevant.

**Comment by carlos-villavicencio-adsk** [comment]
Thanks for the heads up @comeaug. Was there a ticket for that? Otherwise I can create one an prioritize with our team.

Update: Ticket SG-30374 created. Feel free to add more details if needed.

**Pull request closed without merging**
