### PR TITLE
SG-12338 Update urrlib3 version.

### PR DESCRIPTION
**Pull request by willis102**
Update urrlib3 to a newer version while maintaining compatibility with other packages used by CI.

### CODE REVIEW

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c462c0bcdd73a080a03a5430a96d5f7199a8f31b/index.html)

**Comment by manneohrstrom** [comment]
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e8268c4fc5aee98d8bdb77838dd3a7c6778273f7/index.html)

**Comment by willis102** [comment]
I found that urllib3 1.25.3 is compatible with requests / sphinx and [does not have any CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-10210/product_id-35569/Python-Urllib3.html).  I created a [PR on the developer.shotgunsoftware.com repo](https://github.com/shotgunsoftware/developer.shotgunsoftware.com/pull/93) to test CI using this change, and it appears to work both there and here.

**Review by manneohrstrom — APPROVED** [review]
Looks good!!

**Pull request merged**
