### PR TITLE
Update just-the-docs for banner (staged - do not merge)

### PR DESCRIPTION
**Pull request by minna-feng**

### CODE REVIEW

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.ems.autodesk.com/tk-doc-generator/cd16c2414ce6beb1f6bbd14c76a474c50e7a9103/index.html)

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.ems.autodesk.com/tk-doc-generator/2610bf10e07dc72473477bd8499537df7bc22e7f/index.html)

**Review by shaynacohen — APPROVED** [review]
This looks great! Let's wait to merge... I can merge when we're ready to communicate this. Thanks so much, @minna-feng !

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.ems.autodesk.com/tk-doc-generator/3f1d5c1d8dad67d2796db4ac1155941f5d0ae96c/index.html)

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.ems.autodesk.com/tk-doc-generator/bcba76b2670f86f72d968075ab026e410afbc828/index.html)

**Review by NorberMV — APPROVED** [review]
LGTM!

**Comment by ghost** [comment]
[Documentation Preview](http://sg-devdocs.ems.autodesk.com/tk-doc-generator/bfd99988c31e1cc766137d6ffe4d605533095895/index.html)

**Pull request merged**
